---
title: "Published social network surveys and software"
author: "[Raffaele Vacca](https://www.raffaelevacca.com/)"
date: '`r Sys.Date()`'
output:
  knitr:::html_vignette:
  number_sections: yes 
---

This is a list of 

1. Published social network [surveys](#surveys) with links to questionnaires and codebooks.
2. Software [programs](#software) for social network data collection. 

[View on GitHub](https://github.com/raffaelevacca/Open-social-network-surveys).

This is a work in progress, please [contact me](https://www.raffaelevacca.com/) or add a [GitHub issue](https://github.com/raffaelevacca/Open-social-network-surveys) for any feedback or suggestions of more surveys and software.
  
# Surveys

```{r, echo = FALSE, message = FALSE}
library(DT)
library(tidyverse)
library(magrittr)

# Read the data
data.surveys <- read_csv("./Data/surveys.csv")

# Convert markdown links to html links
data.surveys %<>%
  mutate(
    Links = str_replace_all(Links,
            "\\[([^\\]]+)\\]\\(([^\\)]+)\\)",
            "\\<a target=_blank href=\\2>\\1</a>")
  )

# Export to datatable
DT::datatable(data.surveys, escape = FALSE)
```

# Software

```{r, echo=FALSE, message = FALSE}
# Same as above
read_csv("./Data/software.csv") %>%
  # Across all columns
  mutate(across(everything(),
                ~ str_replace_all(.x,
                            "\\[([^\\]]+)\\]\\(([^\\)]+)\\)",
                            "\\<a target=_blank href=\\2>\\1</a>")
  )
  ) %>%
  DT::datatable(., escape = FALSE)
```